version: "3.8"

volumes:
  data-persist:

services:
  db:
    image: postgres:12
    expose:
      - 5432
    volumes:
      # startup scripts are run when the container is created
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # this folder either with docker volume or local persists the data 
      # across containers
      - data-persist:/var/lib/postgresql/data
      # dynamic access for scripts
      - .:/app
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: pguser
      POSTGRES_DB: defaultdb
